In [20]:
#grouping customers based on their purcchasing behavior
import numpy as np
import pandas as pd
df = pd.read_csv('marketing_data.csv')
print(df)
data = df.iloc[:, 10:15]
print(data)

         ID  Year_Birth   Education Marital_Status       Income  Kidhome  \
0      1826        1970  Graduation       Divorced  $84,835.00         0   
1         1        1961  Graduation         Single  $57,091.00         0   
2     10476        1958  Graduation        Married  $67,267.00         0   
3      1386        1967  Graduation       Together  $32,474.00         1   
4      5371        1989  Graduation         Single  $21,474.00         1   
...     ...         ...         ...            ...          ...      ...   
2235  10142        1976         PhD       Divorced  $66,476.00         0   
2236   5263        1977    2n Cycle        Married  $31,056.00         1   
2237     22        1976  Graduation       Divorced  $46,310.00         1   
2238    528        1978  Graduation        Married  $65,819.00         0   
2239   4070        1969         PhD        Married  $94,871.00         0   

      Teenhome Dt_Customer  Recency  MntWines  ...  NumStorePurchases  \
0            0

In [21]:
X = data.values
print(X)

[[104 379 111 189 218]
 [  5  64   7   0  37]
 [ 11  59  15   2  30]
 ...
 [  2  88  15   5  14]
 [ 38 701 149 165  63]
 [ 24 553 188   0 144]]


In [22]:
def find_closest_centroids(X, centroids):
    #centroids have the same number of features as X
    """
    Computes the centroid memberships for every example
    
    Args:
        X (ndarray): (m, n) Input values      
        centroids (ndarray): (K, n) centroids
    
    Returns:
        idx (array_like): (m,) closest centroids
    
    """

    # Set K
    K = centroids.shape[0]
    # You need to return the following variables correctly
    idx = np.zeros(X.shape[0], dtype=int)
    ### START CODE HERE ###
    for i in range(X.shape[0]):
        #iterate through each training example and set distances to empty array on each iteration
        distances = []
        for j in range(K):
            #find distance of training example to each centroid and append to array
            distances.append(np.linalg.norm(X[i] - centroids[j]))
           
        idx[i] = np.argmin(distances)
    
        
        
            
            
        
     ### END CODE HERE ###
    
    return idx

In [23]:
#Creating a 100 different clusters for the dataset
K = 100
def kMeans_init_centroids(X, K):
    """
    This function initializes K centroids that are to be 
    used in K-Means on the dataset X
    
    Args:
        X (ndarray): Data points 
        K (int):     number of centroids/clusters
    
    Returns:
        centroids (ndarray): Initialized centroids
    """
    
    # Randomly reorder the indices of examples
    randidx = np.random.permutation(X.shape[0])
    
    # Take the first K examples as centroids
    centroids = X[randidx[:K]]
    
    return centroids

In [24]:
initial_centroids = kMeans_init_centroids(X, K)
idx = find_closest_centroids(X, initial_centroids)
print(idx[:5])

[23 48  2 67 94]


In [25]:
def compute_centroids(X, idx, K):
    """
    Returns the new centroids by computing the means of the 
    data points assigned to each centroid.
    
    Args:
        X (ndarray):   (m, n) Data points
        idx (ndarray): (m,) Array containing index of closest centroid for each 
                       example in X. Concretely, idx[i] contains the index of 
                       the centroid closest to example i
        K (int):       number of centroids
    
    Returns:
        centroids (ndarray): (K, n) New centroids computed
    """
    
    # Useful variables
    m, n = X.shape
    
    # You need to return the following variables correctly
    centroids = np.zeros((K, n))
    
    ### START CODE HERE ###
    for j in range(K):
        C_k = []
    #for each centroid
        for index,value in enumerate(idx):
            #iterating through each centroid and comparing it's index to the centroid index closest to each training example
            #and appending training examples with for each index to a list and finding the mean of that list. then
            #assigning the mean as the new centroid
            #centroids 
            if j == value:
                C_k.append(X[index])
        #find mean of all rtraining examples
        centroids[j] = np.mean(C_k, axis=0)
            
        
        
    ### END CODE HERE ## 
    
    return centroids

In [26]:

centroids = compute_centroids(X, idx, K)
print(centroids)

[[8.27272727e+00 3.05000000e+01 9.90909091e+00 6.90909091e+00
  4.21363636e+01]
 [1.37500000e+01 2.33916667e+02 3.14166667e+01 6.59166667e+01
  2.16666667e+01]
 [1.87407407e+01 5.84444444e+01 2.09629630e+01 1.06296296e+01
  2.66296296e+01]
 [1.42857143e+01 2.02142857e+01 1.06428571e+01 4.57142857e+00
  9.14285714e+00]
 [4.41176471e+00 8.80000000e+01 1.17058824e+01 7.82352941e+00
  7.94705882e+01]
 [2.35714286e+00 4.34285714e+01 3.50000000e+00 4.07142857e+00
  1.88571429e+01]
 [4.92307692e+00 7.66153846e+01 5.84615385e+00 5.15384615e+00
  1.70923077e+02]
 [4.39459459e+01 9.74864865e+01 8.48918919e+01 5.98648649e+01
  3.14054054e+01]
 [1.45625000e+02 2.78375000e+02 4.91250000e+01 4.61250000e+01
  4.41250000e+01]
 [3.72222222e+00 7.00000000e+00 2.03333333e+01 3.16666667e+00
  1.80000000e+01]
 [2.52727273e+01 3.85454545e+02 5.56363636e+01 7.97727273e+01
  4.80454545e+01]
 [1.19354839e+00 1.23870968e+01 2.35483871e+00 2.90322581e+00
  1.93225806e+01]
 [6.48125000e+01 4.42906250e+02 6.706250

In [30]:
def run_kMeans(X, initial_centroids, max_iters=10, plot_progress=False):
    """
    Runs the K-Means algorithm on data matrix X, where each row of X
    is a single example
    """
    
    # Initialize values
    m, n = X.shape
    K = initial_centroids.shape[0]
    centroids = initial_centroids
    previous_centroids = centroids    
    idx = np.zeros(m)

    # Run K-Means
    for i in range(max_iters):
        
        #Output progress
        print("K-Means iteration %d/%d" % (i, max_iters-1))
        
        # For each example in X, assign it to the closest centroid
        idx = find_closest_centroids(X, centroids)
        
            
        # Given the memberships, compute new centroids
        centroids = compute_centroids(X, idx, K)
    return centroids, idx

In [33]:
max_iters = 10
c, idx = run_kMeans(X, initial_centroids, max_iters, plot_progress=True)
print(c)
print(idx)

K-Means iteration 0/9
K-Means iteration 1/9
K-Means iteration 2/9
K-Means iteration 3/9
K-Means iteration 4/9
K-Means iteration 5/9
K-Means iteration 6/9
K-Means iteration 7/9
K-Means iteration 8/9
K-Means iteration 9/9
[[1.64666667e+01 2.89333333e+01 2.36000000e+01 1.34666667e+01
  5.04666667e+01]
 [2.96153846e+01 2.44230769e+02 7.08461538e+01 1.11153846e+02
  3.60000000e+01]
 [2.41578947e+01 5.47368421e+01 1.75789474e+01 1.11578947e+01
  2.75263158e+01]
 [1.45000000e+01 2.02142857e+01 1.35714286e+01 4.92857143e+00
  8.21428571e+00]
 [6.00000000e+00 8.54210526e+01 1.17894737e+01 9.10526316e+00
  7.90526316e+01]
 [3.00000000e+00 4.47096774e+01 6.09677419e+00 5.25806452e+00
  1.80000000e+01]
 [5.93750000e+00 5.65625000e+01 1.07500000e+01 8.37500000e+00
  1.87750000e+02]
 [3.83600000e+01 1.02640000e+02 1.44240000e+02 4.83600000e+01
  4.00400000e+01]
 [1.12894737e+02 2.72736842e+02 6.53684211e+01 4.96842105e+01
  5.85789474e+01]
 [3.31250000e+00 8.62500000e+00 2.48125000e+01 3.06250000e+0

In [34]:
cdp = []
#centroids data points
for j in range(K):
    cdp_i = []
    #for each centroid
    for index,value in enumerate(idx):
        if j == value:
            cdp_i.append(index)
            #iterating through each centroid and comparing it's index to the centroid index closest to each training example
            #and appending index of each training examples to a list 
    cdp.append(cdp_i)
print(cdp[0])

[73, 279, 280, 562, 611, 709, 930, 998, 1245, 1320, 1412, 1581, 1598, 2052, 2053]


In [35]:
#The first group of customers with similar purchasing behavior are customers with 
for person in cdp[0]:
    details = df.iloc[person]
    print(details)
    
    

ID                            3887
Year_Birth                    1970
Education               Graduation
Marital_Status              Single
Income                 $27,242.00 
Kidhome                          1
Teenhome                         0
Dt_Customer               11/11/12
Recency                          2
MntWines                         3
MntFruits                       17
MntMeatProducts                 26
MntFishProducts                 20
MntSweetProducts                 1
MntGoldProds                    39
NumDealsPurchases                2
NumWebPurchases                  2
NumCatalogPurchases              0
NumStorePurchases                3
NumWebVisitsMonth                9
AcceptedCmp3                     0
AcceptedCmp4                     0
AcceptedCmp5                     0
AcceptedCmp1                     0
AcceptedCmp2                     0
Response                         1
Complain                         0
Country                        IND
Name: 73, dtype: obj

In [ ]:
#the set of IDs printed above have the same purchasing behavior